### PR TITLE
Change testing framework to xUnit

### PR DESCRIPTION
**Pull request by BZngr**
Also installs Moq mocking framework

Replaces PR #66 based on recent discussion in Discord

### CODE REVIEW

**Review by retailcoder — APPROVED** [review]

**Review by Vogel612 — APPROVED** [review]

**Comment by Greedquest** [comment]
Out of interest, how do you invoke these tests from the command line, so I can review the github action pr I was making

**Comment by BZngr** [comment]
@Greedquest  I found [this](https://xunit.net/docs/getting-started/netcore/cmdline) which may be useful.

**Comment by Greedquest** [comment]
Thanks @BZngr that looks very detailed. I also wanted to check if there was a particular set of flags you use to run the tests in this PR. I guess you just run them in visual studio and it "works"?

Looks like you have set up everything you need to run the tests with dotnet test, although I don't know if I have to supply the .sln file or the Tests/Rubberduck.Tests/Rubberduck.Tests.csproj file. Does the sln file contain the metadata to identify projects that have tests?

**Comment by BZngr** [comment]
> Does the sln file contain the metadata to identify projects that have tests?

Nothing in the `sln` file that I can see.  The metadata you are looking for is in the `*.csproj` files.  Starting from the `sln` file, there are paths to all the `.csproj` files in the solution.  So, there is a way to "get there" from the `sln` file.  

In this PR, see file `Tests/Rubberduck.Tests/Rubberduck.Tests.csproj` lines 21 and 22.  The line 21 identifies the test framework.  And, the test 'runner' (line 22) enables it to just "work" with the visual studio test explorer.  

FWIW, I accidently discovered that multiple test frameworks (and _runner_ adapters) could be concurrently present (and work) within the test project's `csproj` file .  The test code files/classes identify which testing framework to use.

**Pull request merged**
